### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by tot-ra** [sdizdarevic/beedetectionyolov5#1]
Hey. Interesting article/project.
I'd suggest to add a LICENSE so it would be clear who/when can use the weights

Also, would be nice to join forces under @[gratheon](https://github.com/Gratheon) project

**Comment by sdizdarevic** [comment]
Hi, 
Thanks for suggestion.
Repository sdizdarevic/beedetectionyolov5 is licensed under the MIT License.
Best regards,
sdizdarevic
